import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { Navigation } from "@/components/navigation";
import { IntroProvider } from "@/components/intro-provider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="preload"
          href="/fonts/safiro/Safiro-SemiBold.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/safiro/Safiro-Bold.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
      </head>
      <body
        className={`${geistSans.variable} antialiased`}
      >
        <IntroProvider>
          <Navigation />
          {children}
        </IntroProvider>
      </body>
    </html>
  );
}
